name: quizmathapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: 2.5.3
  cupertino_icons: ^1.0.2
  dio: 4.0.0
  firebase_core: 1.7.0
  firebase_storage: 10.0.4
  flutter:
    sdk: flutter
  flutter_spinkit: 5.1.0
  flutter_tex: 4.0.3
  get: 4.3.8
  google_fonts: 2.1.0
  lottie: ^1.2.1
  open_file: 3.2.1
  path_provider: 2.0.5
  percent_indicator: 3.4.0
  url_launcher: 6.0.12
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  assets:
    - assets/gambar/
    - assets/icon/
  uses-material-design: true
